### ISSUE TITLE
Cosmetic updates

### ISSUE THREAD

**Issue by xxdunedainxx** [xxdunedainxx/lindsay-wildlife-treasure-hunt#145]
- Start Game button should be circle instead of rectangle
- Circular buttons should be green?
- "You win!" to "you are a successful explorer"
-  Move scanner and question around
- "Level #" at top to "Question #" 
- “Can you please increase the contrast between the clue text and background with a darker text color?”
- No need to mention Lindsay. The LWE logo is at the top.
- Can you please move the Lindsay logo to the far left of the top bar? 
- Wn message updates, see: https://docs.google.com/document/d/1wryhq-vp1Saie_E3nSWDVMeBiT13OgpQE7TUXFwfKv8/edit
- Consolidate start-game and homepage into one page

**Comment by rjmacleod** [comment]
- Fix Firefox dropdown menu bullet point formatting
